version: '3.8'

services:
  demo:
    build: .
    command: poetry run python manage.py runserver 8000
    ports:
      - 8000:8000
    depends_on:
      - scylla
  scylla:
    image: scylladb/scylla:5.1
    command: --smp 1 --memory 750M --overprovisioned 1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "10000:10000"
